
title_template: "Aimee • %s"
title: Personal information manager
description: Aimee is your friendly information managager with notes, tasks, and schedules all in one pleasant place.
brand: Aimee
globals: [global]
libs: [lib]
favicon: /img/favicon.png
logo: /img/logo.svg
router: true
css_2023: true

main_navi:
  - Changelog
  - Pricing
  - About

footer_navi:
  Product:
    - Features
    - Integrations
    - Pricing
    - Changelog
    - Docs

  Company:
    - About us
    - Blog
    - Careers
    - Customers
    - Brand

  Resources:
    - Startup Program
    - Community
    - Contact
    - Privacy Policy
    - Terms of service

  Developers:
    - API
    - Templates
    - Status
    - GitHub
    - README